version: '3.6'
services:
  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54323:5432"
    restart: always

#  backend:
#    restart: always
#    container_name: backend
#    build: ./server
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=root
#
#  frontend:
#    restart: always
#    container_name: frontend
#    build: ./frontend/shelter-app
#    depends_on:
#      - backend
#    environment:
#      - REACT_APP_API_URL=http://localhost/api
#  nginx:
#    image: nginx:alpine
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"
#    depends_on:
#      - frontend